### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by colmex**
changed the references of BitCumulus to Metadisk

### CODE REVIEW

**Comment by EmergentBehavior** [comment]
The references in the deploy scripts and web-core need to be updated before the nginx example can be updated.

**Comment by colmex** [comment]
that would be the ones here right? https://github.com/Storj/web-core/blob/master/INSTALL.md 
and where are the deploy scripts?

Edit: nvm the deploy scripts are the Storj/lunchbox right?

**Comment by EmergentBehavior** [comment]
Yup.

**Comment by EmergentBehavior** [comment]
Going to do a thorough review of this now and update all references in lunchbox.

**Pull request closed without merging**
